export const UPDATE_AUTH = "UPDATE_AUTH";
export const LOGOUT = "LOGOUT";
export const UPDATE_FAV = "UPDATE_FAV";
export const UPDATE_WATCH = "UPDATE_WATCH";
export const FETCH_REQUEST_AUTH = "FETCH_REQUEST_AUTH";
export const FETCH_SUCCESS_AUTH = "FETCH_SUCCESS_AUTH";
export const FETCH_ERROR_AUTH = "FETCH_ERROR_AUTH";
